### ISSUE TITLE
Version of lasagne?

### ISSUE THREAD

**Issue by 317070** [skaae/recurrent-spatial-transformer-code#2]
I have trouble running these. For which version of Lasagne should they work?

> Traceback (most recent call last):
>  File "ffn_spn.py", line 67, in <module>
>    sh_drp = theano.shared(lasagne.utils.floatX(args.dropout))
>  File "/home/jdgrave/python_modules/lasagne/utils.py", line 12, in floatX
>    return arr.astype(theano.config.floatX)
> AttributeError: 'float' object has no attribute 'astype'

**Comment by skaae** [comment]
I just checked with a newly updated lasagne. 
I can do:

``` Python
import theano
import lasagne
sh_drp = theano.shared(lasagne.utils.floatX(1.0))
```

Which should be identical. Can you check if that code runs on your system? 

My numpy version is '1.9.3', maybe that matters.

**Comment by 317070** [comment]
Ah, it appears my system used the wrong version of lasagne instead of the installed one! Thx!
