### ISSUE TITLE
l_conv3_out

### ISSUE THREAD

**Issue by BenjaminBossan** [skaae/recurrent-spatial-transformer-code#3]
Hi, I noticed that in your [ffn script](https://github.com/skaae/recurrent-spatial-transformer-code/blob/master/ffn_spn.py#L160) you define `l_conv3_out` but don't seem to use it, your `l_class1` uses `l_conv3_out` instead. Is this unintentional and if so does it affect the result?

**Comment by skaae** [comment]
I think that was unintentinal. Don't think i'tll affect the results very much though

**Comment by BenjaminBossan** [comment]
Alright, shall I close the issue :)

**Comment by skaae** [comment]
no need to, i'll do it.
